# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  name: ty
  version: "0.0.1a20"

package:
  name: "${{ name|lower }}"
  version: "${{ version }}"

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 933b65a152f277aa0e23ba9027e5df2c2cc09e18293e87f2a918658634db5f15

build:
  number: 1
  script:
    content:
      - maturin build --release
      - ${{ PYTHON }} -m pip install --find-links=ruff/target/wheels ty
      - cd ruff
      - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

  python:
    version_independent: true

requirements:
  build:
    - cargo-bundle-licenses
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - if: build_platform != target_platform
      then:
        - python ${{ python_min }}.*
        - cross-python_${{ target_platform }}
        - maturin >=1.0,<2
  host:
    - python ${{ python_min }}.*
    - python-abi3
    - maturin >=1.0,<2
    - pip
  run:
    - python
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}

tests:
  - python:
      imports:
        - ty
  - script:
      - ty --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An extremely fast Python type checker and language server, written in Rust.
  homepage: https://github.com/astral-sh/ty
  repository: https://github.com/astral-sh/ty

extra:
  recipe-maintainers:
    - pavelzw
